corrected resources on pipeline

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -108,9 +108,13 @@ jobs:
 
           SOURCE_CSS_DIR: /home/printsh1/printshopeld/release/${{github.sha}}/public/css
           SOURCE_JS_DIR: /home/printsh1/printshopeld/release/${{github.sha}}/public/js
+          SOURCE_ASSET_DIR: /home/printsh1/printshopeld/release/${{github.sha}}/public/assets
+          SOURCE_ADMIN_DIR: /home/printsh1/printshopeld/release/${{github.sha}}/public/admin
 
           DEST_CSS_DIR: /home/printsh1/public_html/css
           DEST_JS_DIR: /home/printsh1/public_html/js
+          DEST_ASSET_DIR: /home/printsh1/public_html/assets
+          DEST_ADMIN_DIR: /home/printsh1/public_html/admin
 
           DEST_PARENT_DIR: /home/printsh1/public_html
         with:
@@ -170,6 +174,44 @@ jobs:
                 echo "js directory does not exist in the source."
             fi
             # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            if [ -d "$SOURCE_ASSET_DIR" ]; then
+                if [ -d "$DEST_ASSET_DIR" ]; then
+                    rm -rf "$DEST_ASSET_DIR"
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to remove the destination asset directory."
+                        exit 1
+                    fi
+                else
+                    echo "asset directory does not exist in the destination."
+                fi
+                mv "$SOURCE_ASSET_DIR" "$DEST_PARENT_DIR"
+                if [ $? -ne 0 ]; then
+                    echo "Failed to move the asset directory from source to destination."
+                    exit 1
+                fi
+            else
+                echo "asset directory does not exist in the source."
+            fi
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+            if [ -d "$SOURCE_ADMIN_DIR" ]; then
+                if [ -d "$DEST_ADMIN_DIR" ]; then
+                    rm -rf "$DEST_ADMIN_DIR"
+                    if [ $? -ne 0 ]; then
+                        echo "Failed to remove the destination admin directory."
+                        exit 1
+                    fi
+                else
+                    echo "admin directory does not exist in the destination."
+                fi
+                mv "$SOURCE_ADMIN_DIR" "$DEST_PARENT_DIR"
+                if [ $? -ne 0 ]; then
+                    echo "Failed to move the admin directory from source to destination."
+                    exit 1
+                fi
+            else
+                echo "admin directory does not exist in the source."
+            fi
+            # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
             # ++++++++++++++++++++++++++++++++++++++++++++++First time++++++++++++++++++++++++++++++++++++++++++++++
             # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
             # mv -f "/home/printsh1/printshopeld/release/${GITHUB_SHA}/public/.htaccess" "/home/printsh1/public_html"
@@ -188,7 +230,7 @@ jobs:
             rm -rf /home/printsh1/printshopeld/release/${GITHUB_SHA}/public/mix-manifest.json
             rm -rf /home/printsh1/printshopeld/release/${GITHUB_SHA}/public/web.config
             # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
-            # rm -rf /home/printsh1/printshopeld/release/${GITHUB_SHA}/public/
+            rm -rf /home/printsh1/printshopeld/release/${GITHUB_SHA}/public/
             # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 
   # Run befor-hook
